# Generated by Django 4.2.7 on 2023-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_level', models.CharField(choices=[('NB', 'Not busy'), ('MB', 'Moderately Busy'), ('VB', 'Very busy')], default='NB', max_length=2)),
                ('comfort_level', models.CharField(choices=[('VC', 'Very comfortable'), ('MC', 'Moderately comfortable'), ('NC', 'Not comfortable')], default='VC', max_length=2)),
                ('wifi_situation', models.CharField(choices=[('NW', 'No WIFI'), ('PW', 'WIFI, but must be paid'), ('FW', 'WIFI, Free')], default='NW', max_length=2)),
                ('noise_level', models.CharField(choices=[('QZ', 'Quiet enough for a zoom meeting'), ('MN', 'Moderate noise'), ('VN', 'Very noisy')], default='QZ', max_length=2)),
                ('parking_situation', models.CharField(choices=[('EP', 'Very easy parking'), ('MP', 'Moderate parking'), ('DP', 'Very difficult parking')], default='EP', max_length=2)),
            ],
        ),
    ]
