# Generated by Django 4.2.7 on 2023-11-19 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('yelp_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_level', models.IntegerField(blank=True, choices=[(0, 'Very busy'), (1, 'Moderately Busy'), (2, 'Not busy')], default=None, null=True)),
                ('comfort_level', models.IntegerField(blank=True, choices=[(0, 'Not comfortable'), (1, 'Moderately comfortable'), (2, 'Very comfortable')], default=None, null=True)),
                ('wifi_situation', models.IntegerField(blank=True, choices=[(0, 'No WIFI'), (1, 'WIFI, but must be paid'), (2, 'WIFI, Free')], default=None, null=True)),
                ('noise_level', models.IntegerField(blank=True, choices=[(0, 'Very noisy'), (1, 'Moderate noise'), (2, 'Quiet enough for a zoom meeting')], default=None, null=True)),
                ('parking_situation', models.IntegerField(blank=True, choices=[(0, 'Very difficult parking'), (1, 'Moderate parking'), (2, 'Very easy parking')], default=None, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spot.location')),
            ],
        ),
    ]
