# Generated by Django 4.2.7 on 2023-11-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='yelp_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
