# Generated by Django 4.2.7 on 2023-11-18 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_location_survey_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='busy_str',
            field=models.CharField(choices=[(0, 'Very busy'), (1, 'Moderately Busy'), (2, 'Not busy')], default=None),
        ),
        migrations.AddField(
            model_name='survey',
            name='comfort_str',
            field=models.CharField(choices=[(0, 'Not comfortable'), (1, 'Moderately comfortable'), (2, 'Very comfortable')], default=None),
        ),
        migrations.AddField(
            model_name='survey',
            name='noise_str',
            field=models.CharField(choices=[(0, 'Very noisy'), (1, 'Moderate noise'), (2, 'Quiet enough for a zoom meeting')], default=None),
        ),
        migrations.AddField(
            model_name='survey',
            name='parking_str',
            field=models.CharField(choices=[(0, 'Very difficult parking'), (1, 'Moderate parking'), (2, 'Very easy parking')], default=None),
        ),
        migrations.AddField(
            model_name='survey',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 12, 20, 50, 590422)),
        ),
        migrations.AddField(
            model_name='survey',
            name='wifi_str',
            field=models.CharField(choices=[(0, 'No WIFI'), (1, 'WIFI, but must be paid'), (2, 'WIFI, Free')], default=None),
        ),
        migrations.AlterField(
            model_name='survey',
            name='busy_level',
            field=models.IntegerField(choices=[(0, 'Very busy'), (1, 'Moderately Busy'), (2, 'Not busy')], default=None),
        ),
        migrations.AlterField(
            model_name='survey',
            name='comfort_level',
            field=models.IntegerField(choices=[(0, 'Not comfortable'), (1, 'Moderately comfortable'), (2, 'Very comfortable')], default=None),
        ),
        migrations.AlterField(
            model_name='survey',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spot.location'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='noise_level',
            field=models.IntegerField(choices=[(0, 'Very noisy'), (1, 'Moderate noise'), (2, 'Quiet enough for a zoom meeting')], default=None),
        ),
        migrations.AlterField(
            model_name='survey',
            name='parking_situation',
            field=models.IntegerField(choices=[(0, 'Very difficult parking'), (1, 'Moderate parking'), (2, 'Very easy parking')], default=None),
        ),
        migrations.AlterField(
            model_name='survey',
            name='wifi_situation',
            field=models.IntegerField(choices=[(0, 'No WIFI'), (1, 'WIFI, but must be paid'), (2, 'WIFI, Free')], default=None),
        ),
    ]
